from factor_engine.optimizer.prompts_opt import (
    CODER_PROMPT_TEMPLATE,
    DOCTOR_SYSTEM_BASE,
    DOCTOR_TABLE_SYSTEM_PROMPT,
    DOCTOR_TABLE_USER_TEMPLATE,
    DOCTOR_USER_TEMPLATE,
    JUDGE_SYSTEM_PROMPT,
    JUDGE_USER_TEMPLATE,
    REFEREE_PROMPT,
)

